import { SevereIllnessDiseaseAcceptancePossibleInfo } from './model'

export const emergencyRoomRealTimeUsefulStockbedInfoList = {
  response: {
    header: {
      resultCode: 0,
      resultMsg: 'NORMAL SERVICE.',
    },
    body: {
      items: {
        item: [
          {
            dutyName: '연세대학교의과대학강남세브란스병원',
            dutyTel3: '02-2019-3333',
            hpid: 'A1100015',
            hv10: 'Y',
            hv11: 'Y',
            hv28: 2,
            hv29: 1,
            hv30: 2,
            hv34: 5,
            hv41: 5,
            hv42: 'Y',
            hv5: 'Y',
            hv6: 2,
            hv7: 'Y',
            hvamyn: 'Y',
            hvangioayn: 'Y',
            hvcrrtayn: 'Y',
            hvctayn: 'Y',
            hvec: 4,
            hvecmoayn: 'Y',
            hvgc: 398,
            hvhypoayn: 'Y',
            hvicc: 6,
            hvidate: 20240310215715,
            hvincuayn: 'Y',
            hvmriayn: 'Y',
            hvncc: 2,
            hvoc: 23,
            hvoxyayn: 'N1',
            hvs01: 15,
            hvs02: 2,
            hvs03: 1,
            hvs04: 2,
            hvs08: 28,
            hvs12: 12,
            hvs15: 8,
            hvs17: 29,
            hvs22: 23,
            hvs25: 5,
            hvs26: 1,
            hvs27: 4,
            hvs28: 3,
            hvs29: 6,
            hvs30: 47,
            hvs31: 10,
            hvs32: 23,
            hvs33: 6,
            hvs34: 3,
            hvs35: 5,
            hvs38: 763,
            hvventiayn: 'Y',
            hvventisoayn: 'Y',
            phpid: 'A1100015',
            rnum: 1,
          },
          {
            dutyName: '삼성서울병원',
            dutyTel3: '02-3410-2060',
            hpid: 'A1100010',
            hv10: 'Y',
            hv11: 'Y',
            hv2: 18,
            hv28: 2,
            hv29: 2,
            hv3: 16,
            hv30: 2,
            hv32: 7,
            hv34: 0,
            hv35: 2,
            hv40: 9,
            hv41: 11,
            hv42: 'Y',
            hv5: 'Y',
            hv6: 4,
            hv7: 'Y',
            hvamyn: 'Y',
            hvangioayn: 'Y',
            hvccc: 19,
            hvcrrtayn: 'Y',
            hvctayn: 'Y',
            hvec: 50,
            hvecmoayn: 'Y',
            hvgc: 849,
            hvhypoayn: 'Y',
            hvicc: 3,
            hvidate: 20240310215623,
            hvincuayn: 'Y',
            hvmriayn: 'Y',
            hvncc: 12,
            hvoc: 54,
            hvoxyayn: 'N1',
            hvs01: 59,
            hvs02: 4,
            hvs03: 2,
            hvs04: 2,
            hvs06: 30,
            hvs07: 23,
            hvs08: 59,
            hvs09: 15,
            hvs12: 12,
            hvs15: 12,
            hvs16: 25,
            hvs17: 10,
            hvs18: 2,
            hvs22: 56,
            hvs24: 16,
            hvs25: 12,
            hvs26: 7,
            hvs27: 17,
            hvs28: 13,
            hvs29: 14,
            hvs30: 130,
            hvs31: 18,
            hvs32: 42,
            hvs33: 19,
            hvs34: 10,
            hvs35: 2,
            hvs38: 1674,
            hvventiayn: 'Y',
            hvventisoayn: 'Y',
            phpid: 'A1100010',
            rnum: 2,
          },
        ],
      },
      numOfRows: 10,
      pageNo: 1,
      totalCount: 2,
    },
  },
}

export const severeIllnessDiseaseAcceptancePossibleInfoList = {
  response: {
    header: {
      resultCode: 0,
      resultMsg: 'NORMAL SERVICE.',
    },
    body: {
      items: {
        item: [
          {
            dutyName: 'A1100015',
            MKioskTy1: 'Y',
            MKioskTy2: 'Y',
            MKioskTy3: 'Y',
            MKioskTy4: 'Y',
            MKioskTy5: 'Y',
            MKioskTy6: 'Y',
            MKioskTy7: 'Y',
            MKioskTy8: 'Y',
            MKioskTy9: 'Y',
            MKioskTy10: '정보미제공',
            MKioskTy11: 'Y',
            MKioskTy12: '정보미제공',
            MKioskTy12Msg: '.',
            MKioskTy13: '정보미제공',
            MKioskTy14: '정보미제공',
            MKioskTy14Msg: '.',
            MKioskTy15: 'Y',
            MKioskTy15Msg: '500g',
            MKioskTy16: 'Y',
            MKioskTy17: 'Y',
            MKioskTy18: 'Y',
            MKioskTy19: 'Y',
            MKioskTy20: '정보미제공',
            MKioskTy21: '정보미제공',
            MKioskTy22: '정보미제공',
            MKioskTy23: '정보미제공',
            MKioskTy24: '정보미제공',
            MKioskTy25: 'Y',
            MKioskTy26: '정보미제공',
            MKioskTy27: '정보미제공',
            MKioskTy28: 'Y',
            MKioskTy27Msg: '.',
          },
          {
            dutyName: 'A1100010',
            MKioskTy1: 'Y',
            MKioskTy2: 'Y',
            MKioskTy3: 'Y',
            MKioskTy4: 'Y',
            MKioskTy5: 'Y',
            MKioskTy6: 'Y',
            MKioskTy7: 'Y',
            MKioskTy8: '정보미제공',
            MKioskTy9: 'Y',
            MKioskTy10: 'Y',
            MKioskTy10Msg: '연령제한 없음.',
            MKioskTy11: 'Y',
            MKioskTy12: 'Y',
            MKioskTy12Msg: '연령제한 없음',
            MKioskTy13: '정보미제공',
            MKioskTy14: 'Y',
            MKioskTy14Msg: '생후 1개월 이상',
            MKioskTy15: 'Y',
            MKioskTy15Msg: '체중 제한 없음',
            MKioskTy16: 'Y',
            MKioskTy17: 'Y',
            MKioskTy18: 'Y',
            MKioskTy19: '정보미제공',
            MKioskTy20: '정보미제공',
            MKioskTy21: '정보미제공',
            MKioskTy22: 'Y',
            MKioskTy23: 'Y',
            MKioskTy24: 'Y',
            MKioskTy25: 'Y',
            MKioskTy26: 'Y',
            MKioskTy27: 'Y',
            MKioskTy28: 'Y',
            MKioskTy27Msg: '연령제한없음',
          },
        ],
      },
      numOfRows: 30,
      pageNo: 1,
      totalCount: 2,
    },
  },
}
