import { SevereIllnessDiseaseAcceptancePossibleInfo } from './model'

export const emergencyRoomRealTimeUsefulStockbedInfoList = {
  response: {
    header: {
      resultCode: 0,
      resultMsg: 'NORMAL SERVICE.',
    },
    body: {
      items: {
        item: [
          {
            dutyName: '연세대학교의과대학강남세브란스병원',
            dutyTel3: '02-2019-3333',
            hpid: 'A1100015',
            hv10: 'Y',
            hv11: 'Y',
            hv28: 2,
            hv29: 1,
            hv30: 2,
            hv34: 5,
            hv41: 5,
            hv42: 'Y',
            hv5: 'Y',
            hv6: 2,
            hv7: 'Y',
            hvamyn: 'Y',
            hvangioayn: 'Y',
            hvcrrtayn: 'Y',
            hvctayn: 'Y',
            hvec: 4,
            hvecmoayn: 'Y',
            hvgc: 398,
            hvhypoayn: 'Y',
            hvicc: 6,
            hvidate: 20240310215715,
            hvincuayn: 'Y',
            hvmriayn: 'Y',
            hvncc: 2,
            hvoc: 23,
            hvoxyayn: 'N1',
            hvs01: 15,
            hvs02: 2,
            hvs03: 1,
            hvs04: 2,
            hvs08: 28,
            hvs12: 12,
            hvs15: 8,
            hvs17: 29,
            hvs22: 23,
            hvs25: 5,
            hvs26: 1,
            hvs27: 4,
            hvs28: 3,
            hvs29: 6,
            hvs30: 47,
            hvs31: 10,
            hvs32: 23,
            hvs33: 6,
            hvs34: 3,
            hvs35: 5,
            hvs38: 763,
            hvventiayn: 'Y',
            hvventisoayn: 'Y',
            phpid: 'A1100015',
            rnum: 1,
          },
          {
            dutyName: '삼성서울병원',
            dutyTel3: '02-3410-2060',
            hpid: 'A1100010',
            hv10: 'Y',
            hv11: 'Y',
            hv2: 18,
            hv28: 2,
            hv29: 2,
            hv3: 16,
            hv30: 2,
            hv32: 7,
            hv34: 0,
            hv35: 2,
            hv40: 9,
            hv41: 11,
            hv42: 'Y',
            hv5: 'Y',
            hv6: 4,
            hv7: 'Y',
            hvamyn: 'Y',
            hvangioayn: 'Y',
            hvccc: 19,
            hvcrrtayn: 'Y',
            hvctayn: 'Y',
            hvec: 50,
            hvecmoayn: 'Y',
            hvgc: 849,
            hvhypoayn: 'Y',
            hvicc: 3,
            hvidate: 20240310215623,
            hvincuayn: 'Y',
            hvmriayn: 'Y',
            hvncc: 12,
            hvoc: 54,
            hvoxyayn: 'N1',
            hvs01: 59,
            hvs02: 4,
            hvs03: 2,
            hvs04: 2,
            hvs06: 30,
            hvs07: 23,
            hvs08: 59,
            hvs09: 15,
            hvs12: 12,
            hvs15: 12,
            hvs16: 25,
            hvs17: 10,
            hvs18: 2,
            hvs22: 56,
            hvs24: 16,
            hvs25: 12,
            hvs26: 7,
            hvs27: 17,
            hvs28: 13,
            hvs29: 14,
            hvs30: 130,
            hvs31: 18,
            hvs32: 42,
            hvs33: 19,
            hvs34: 10,
            hvs35: 2,
            hvs38: 1674,
            hvventiayn: 'Y',
            hvventisoayn: 'Y',
            phpid: 'A1100010',
            rnum: 2,
          },
        ],
      },
      numOfRows: 10,
      pageNo: 1,
      totalCount: 2,
    },
  },
}

export const severeIllnessDiseaseAcceptancePossibleInfoList = {
  response: {
    header: {
      resultCode: 0,
      resultMsg: 'NORMAL SERVICE.',
    },
    body: {
      items: {
        item: [
          {
            dutyName: 'A1100015',
            MKioskTy1: 'Y',
            MKioskTy2: 'Y',
            MKioskTy3: 'Y',
            MKioskTy4: 'Y',
            MKioskTy5: 'Y',
            MKioskTy6: 'Y',
            MKioskTy7: 'Y',
            MKioskTy8: 'Y',
            MKioskTy9: 'Y',
            MKioskTy10: '정보미제공',
            MKioskTy11: 'Y',
            MKioskTy12: '정보미제공',
            MKioskTy12Msg: '.',
            MKioskTy13: '정보미제공',
            MKioskTy14: '정보미제공',
            MKioskTy14Msg: '.',
            MKioskTy15: 'Y',
            MKioskTy15Msg: '500g',
            MKioskTy16: 'Y',
            MKioskTy17: 'Y',
            MKioskTy18: 'Y',
            MKioskTy19: 'Y',
            MKioskTy20: '정보미제공',
            MKioskTy21: '정보미제공',
            MKioskTy22: '정보미제공',
            MKioskTy23: '정보미제공',
            MKioskTy24: '정보미제공',
            MKioskTy25: 'Y',
            MKioskTy26: '정보미제공',
            MKioskTy27: '정보미제공',
            MKioskTy28: 'Y',
            MKioskTy27Msg: '.',
          },
          {
            dutyName: 'A1100010',
            MKioskTy1: 'Y',
            MKioskTy2: 'Y',
            MKioskTy3: 'Y',
            MKioskTy4: 'Y',
            MKioskTy5: 'Y',
            MKioskTy6: 'Y',
            MKioskTy7: 'Y',
            MKioskTy8: '정보미제공',
            MKioskTy9: 'Y',
            MKioskTy10: 'Y',
            MKioskTy10Msg: '연령제한 없음.',
            MKioskTy11: 'Y',
            MKioskTy12: 'Y',
            MKioskTy12Msg: '연령제한 없음',
            MKioskTy13: '정보미제공',
            MKioskTy14: 'Y',
            MKioskTy14Msg: '생후 1개월 이상',
            MKioskTy15: 'Y',
            MKioskTy15Msg: '체중 제한 없음',
            MKioskTy16: 'Y',
            MKioskTy17: 'Y',
            MKioskTy18: 'Y',
            MKioskTy19: '정보미제공',
            MKioskTy20: '정보미제공',
            MKioskTy21: '정보미제공',
            MKioskTy22: 'Y',
            MKioskTy23: 'Y',
            MKioskTy24: 'Y',
            MKioskTy25: 'Y',
            MKioskTy26: 'Y',
            MKioskTy27: 'Y',
            MKioskTy28: 'Y',
            MKioskTy27Msg: '연령제한없음',
          },
        ],
      },
      numOfRows: 30,
      pageNo: 1,
      totalCount: 2,
    },
  },
}

export const emergencyTreatmentListInfoList = {
  response: {
    header: {
      resultCode: 0,
      resultMsg: 'NORMAL SERVICE.',
    },
    body: {
      items: {
        item: [
          {
            dutyName: 'A1100017',
            MKioskTy1: 'Y',
            MKioskTy10: 'Y',
            MKioskTy10Msg: '출생직후부터',
            MKioskTy11: 'Y',
            MKioskTy12: 'Y',
            MKioskTy12Msg: '출생직후부터',
            MKioskTy13: 'Y',
            MKioskTy14: 'Y',
            MKioskTy14Msg: '출생직후부터',
            MKioskTy15: 'Y',
            MKioskTy15Msg: '출생직후부터',
            MKioskTy16: 'Y',
            MKioskTy17: 'Y',
            MKioskTy18: 'Y',
            MKioskTy19: '정보미제공',
            MKioskTy2: 'Y',
            MKioskTy20: 'Y',
            MKioskTy21: 'Y',
            MKioskTy22: 'Y',
            MKioskTy23: 'Y',
            MKioskTy24: 'Y',
            MKioskTy25: 'Y',
            MKioskTy26: 'Y',
            MKioskTy27: 'Y',
            MKioskTy27Msg: '출생직후부터',
            MKioskTy28: 'Y',
            MKioskTy3: 'Y',
            MKioskTy4: 'Y',
            MKioskTy5: 'Y',
            MKioskTy6: 'Y',
            MKioskTy7: 'Y',
            MKioskTy8: 'Y',
            MKioskTy9: 'Y',
          },
          {
            dutyName: 'A1100006',
            MKioskTy1: 'Y',
            MKioskTy10: '정보미제공',
            MKioskTy10Msg: '최저연령,체중 제한 없음(정복술가능))',
            MKioskTy11: 'Y',
            MKioskTy12: 'Y',
            MKioskTy12Msg: '최저연령,체중 제한 없음',
            MKioskTy13: '정보미제공',
            MKioskTy14: '정보미제공',
            MKioskTy15: 'Y',
            MKioskTy15Msg: '체중제한 없음',
            MKioskTy16: 'Y',
            MKioskTy17: 'Y',
            MKioskTy18: 'Y',
            MKioskTy19: '정보미제공',
            MKioskTy2: 'Y',
            MKioskTy20: '정보미제공',
            MKioskTy21: '정보미제공',
            MKioskTy22: 'Y',
            MKioskTy23: 'Y',
            MKioskTy24: '정보미제공',
            MKioskTy25: '정보미제공',
            MKioskTy26: 'Y',
            MKioskTy27: '정보미제공',
            MKioskTy28: 'Y',
            MKioskTy3: 'Y',
            MKioskTy4: 'Y',
            MKioskTy5: 'Y',
            MKioskTy6: 'Y',
            MKioskTy7: 'Y',
            MKioskTy8: 'Y',
            MKioskTy9: 'Y',
          },
        ],
      },
      numOfRows: 30,
      pageNo: 1,
      totalCount: 2,
    },
  },
}

export const emergencyTreatmentLocationInfoData = {
  response: {
    header: {
      resultCode: 0,
      resultMsg: 'NORMAL SERVICE.',
    },
    body: {
      items: {
        item: {
          cnt: 74,
          distance: 17.53,
          dutyAddr: '경기도 고양시 덕양구 화수로14번길 55 (화정동)',
          dutyDiv: 'A',
          dutyDivName: '종합병원',
          dutyName: '의료법인명지의료재단명지병원',
          dutyTel1: '031-810-5114',
          endTime: 2400,
          hpid: 'A2100042',
          latitude: 37.64207169115689,
          longitude: 126.83145733035825,
          rnum: 1,
          startTime: 0,
        },
      },
      numOfRows: 1,
      pageNo: 1,
      totalCount: 1,
    },
  },
}

export const emergencyTreatmentBasicInfoData = {
  response: {
    header: {
      resultCode: 0,
      resultMsg: 'NORMAL SERVICE.',
    },
    body: {
      items: {
        item: {
          dgidIdName:
            '가정의학과,내과,마취통증의학과,방사선종양학과,병리과,보건(의료원)소,비뇨기과,산부인과,성형외과,소아청소년과,신경과,신경외과,안과,영상의학과,예방치과,외과,응급의학과,이비인후과,재활의학과,정신건강의학과,정형외과,진단검사의학과,치과교정과,치과보존과,치과보철과,치주과,피부과,핵의학과,흉부외과',
          dutyAddr: '서울특별시 구로구 구로동로 148, 고려대부속구로병원 (구로동)',
          dutyEryn: 1,
          dutyHano: 1081,
          dutyHayn: 1,
          dutyMapimg: '구로구청 인근',
          dutyName: '고려대학교의과대학부속구로병원',
          dutyTel1: '02-2626-1114',
          dutyTel3: '02-2626-1550',
          dutyTime1c: 1730,
          dutyTime1s: 900,
          dutyTime2c: 1730,
          dutyTime2s: 900,
          dutyTime3c: 1730,
          dutyTime3s: 900,
          dutyTime4c: 1730,
          dutyTime4s: 900,
          dutyTime5c: 1730,
          dutyTime5s: 900,
          dutyTime6c: 1200,
          dutyTime6s: 900,
          hpbdn: 1075,
          hperyn: 37,
          hpgryn: 894,
          hpicuyn: 16,
          hpid: 'A1100014',
          hpnicuyn: 20,
          hpopyn: 20,
          hvec: 10,
          hvgc: 99,
          hvncc: -1,
          hvoc: 5,
          MKioskTy1: 'Y',
          MKioskTy10: 'Y',
          MKioskTy11: 'Y',
          MKioskTy2: 'Y',
          MKioskTy25: 'Y',
          MKioskTy3: 'Y',
          MKioskTy4: 'Y',
          MKioskTy5: 'Y',
          MKioskTy6: 'Y',
          MKioskTy7: 'Y',
          MKioskTy8: 'Y',
          MKioskTy9: 'Y',
          postCdn1: 83,
          postCdn2: 8,
          wgs84Lat: 37.49211114525054,
          wgs84Lon: 126.8847449363546,
        },
      },
      numOfRows: 10,
      pageNo: 1,
      totalCount: 1,
    },
  },
}
