export type TraumaCenterSummaryInfo = {
  dutyaddr: string
  dutyemcls: string
  dutyemclsname: string
  dutyname: string
  dutytel1: string
  dutytel3: string
  hpid: string
  phpid: string
  rnum: number
  wgs84lat: number
  wgs84lon: number
}

export type TraumaCenterInfo = {
  dgidIdName: string;
  dutyAddr: string;
  dutyEryn: number;
  dutyHano: number;
  dutyHayn: number;
  dutyMapimg: string;
  dutyName: string;
  dutyTel1: string;
  dutyTel3: string;
  dutyTime1c: number;
  dutyTime1s: number;
  dutyTime2c: number;
  dutyTime2s: number;
  dutyTime3c: number;
  dutyTime3s: number;
  dutyTime4c: number;
  dutyTime4s: number;
  dutyTime5c: number;
  dutyTime5s: number;
  dutyTime6c: number;
  dutyTime6s: number;
  hpbdn: number;
  hperyn: number;
  hpgryn: number;
  hpicuyn: number;
  hpid: string;
  hpnicuyn: number;
  hpopyn: number;
  hvec: number;
  hvgc: number;
  hvncc: number;
  hvoc: number;
  MKioskTy1: string;
  MKioskTy10: string;
  MKioskTy11: string;
  MKioskTy2: string;
  MKioskTy25: string;
  MKioskTy3: string;
  MKioskTy4: string;
  MKioskTy5: string;
  MKioskTy6: string;
  MKioskTy7: string;
  MKioskTy8: string;
  MKioskTy9: string;
  postCdn1: number;
  postCdn2: number;
  wgs84Lat: number;
  wgs84Lon: number;
};