export type EmergencyRoomRealtimeUsefulStockbedInfo = {
  dutyName: string
  dutyTel3: string
  hpid: string
  hv10: string
  hv11: string
  hv28: number
  hv29: number
  hv30: number
  hv34: number
  hv41: number
  hv42: string
  hv5: string
  hv6: number
  hv7: string
  hvamyn: string
  hvangioayn: string
  hvcrrtayn: string
  hvctayn: string
  hvec: number
  hvecmoayn: string
  hvgc: number
  hvhypoayn: string
  hvicc: number
  hvidate: number
  hvincuayn: string
  hvmriayn: string
  hvncc: number
  hvoc: number
  hvoxyayn: string
  hvs01: number
  hvs02: number
  hvs03: number
  hvs04: number
  hvs08: number
  hvs12: number
  hvs15: number
  hvs17: number
  hvs22: number
  hvs25: number
  hvs26: number
  hvs27: number
  hvs28: number
  hvs29: number
  hvs30: number
  hvs31: number
  hvs32: number
  hvs33: number
  hvs34: number
  hvs35: number
  hvs38: number
  hvventiayn: string
  hvventisoayn: string
  phpid: string
  rnum: number
  hv2?: number
  hv3?: number
  hv32?: number
  hv35?: number
  hv40?: number
  hvccc?: number
  hvs06?: number
  hvs07?: number
  hvs09?: number
  hvs16?: number
  hvs18?: number
  hvs24?: number
}

// type YesNo = 'Y' | 'N'

export type SevereIllnessDiseaseAcceptancePossibleInfo = {
  dutyName: string
  MKioskTy1: string
  MKioskTy2: string
  MKioskTy3: string
  MKioskTy4: string
  MKioskTy5: string
  MKioskTy6: string
  MKioskTy7: string
  MKioskTy8: string
  MKioskTy9: string
  MKioskTy10: string
  MKioskTy10Msg?: string
  MKioskTy11: string
  MKioskTy12: string
  MKioskTy12Msg?: string
  MKioskTy13: string
  MKioskTy14: string
  MKioskTy14Msg?: string
  MKioskTy15: string
  MKioskTy15Msg?: string
  MKioskTy16: string
  MKioskTy17: string
  MKioskTy18: string
  MKioskTy19: string
  MKioskTy20: string
  MKioskTy21: string
  MKioskTy22: string
  MKioskTy23: string
  MKioskTy24: string
  MKioskTy25: string
  MKioskTy26: string
  MKioskTy27: string
  MKioskTy27Msg?: string
  MKioskTy28: string
}

export type EmergencyTreatmentListInfo = {
  dutyName: string
  MKioskTy1: string
  MKioskTy2: string
  MKioskTy3: string
  MKioskTy4: string
  MKioskTy5: string
  MKioskTy6: string
  MKioskTy7: string
  MKioskTy8: string
  MKioskTy9: string
  MKioskTy10: string
  MKioskTy10Msg?: string
  MKioskTy11: string
  MKioskTy12: string
  MKioskTy12Msg?: string
  MKioskTy13: string
  MKioskTy14: string
  MKioskTy14Msg?: string
  MKioskTy15: string
  MKioskTy15Msg?: string
  MKioskTy16: string
  MKioskTy17: string
  MKioskTy18: string
  MKioskTy19: string
  MKioskTy20: string
  MKioskTy21: string
  MKioskTy22: string
  MKioskTy23: string
  MKioskTy24: string
  MKioskTy25: string
  MKioskTy26: string
  MKioskTy27: string
  MKioskTy27Msg?: string
  MKioskTy28: string
}

export type EmergencyTreatmentLocationInfo = {
  cnt: number
  distance: number
  dutyAddr: string
  dutyDiv: string
  dutyDivName: string
  dutyName: string
  dutyTel1: string
  endTime: number
  hpid: string
  latitude: number
  longitude: number
  rnum: number
  startTime: number
}

export type EmergencyTreatmentBasicInfo = {
  dgidIdName: string;
  dutyAddr: string;
  dutyEryn: number;
  dutyHano: number;
  dutyHayn: number;
  dutyMapimg: string;
  dutyName: string;
  dutyTel1: string;
  dutyTel3: string;
  dutyTime1c: number;
  dutyTime1s: number;
  dutyTime2c: number;
  dutyTime2s: number;
  dutyTime3c: number;
  dutyTime3s: number;
  dutyTime4c: number;
  dutyTime4s: number;
  dutyTime5c: number;
  dutyTime5s: number;
  dutyTime6c: number;
  dutyTime6s: number;
  hpbdn: number;
  hperyn: number;
  hpgryn: number;
  hpicuyn: number;
  hpid: string;
  hpnicuyn: number;
  hpopyn: number;
  hvec: number;
  hvgc: number;
  hvncc: number;
  hvoc: number;
  MKioskTy1: string;
  MKioskTy10: string;
  MKioskTy11: string;
  MKioskTy2: string;
  MKioskTy25: string;
  MKioskTy3: string;
  MKioskTy4: string;
  MKioskTy5: string;
  MKioskTy6: string;
  MKioskTy7: string;
  MKioskTy8: string;
  MKioskTy9: string;
  postCdn1: number;
  postCdn2: number;
  wgs84Lat: number;
  wgs84Lon: number;
}
