export type EmergencyRoomRealtimeUsefulStockbedInfo = {
  dutyName: string
  dutyTel3: string
  hpid: string
  hv10: string
  hv11: string
  hv28: number
  hv29: number
  hv30: number
  hv34: number
  hv41: number
  hv42: string
  hv5: string
  hv6: number
  hv7: string
  hvamyn: string
  hvangioayn: string
  hvcrrtayn: string
  hvctayn: string
  hvec: number
  hvecmoayn: string
  hvgc: number
  hvhypoayn: string
  hvicc: number
  hvidate: number
  hvincuayn: string
  hvmriayn: string
  hvncc: number
  hvoc: number
  hvoxyayn: string
  hvs01: number
  hvs02: number
  hvs03: number
  hvs04: number
  hvs08: number
  hvs12: number
  hvs15: number
  hvs17: number
  hvs22: number
  hvs25: number
  hvs26: number
  hvs27: number
  hvs28: number
  hvs29: number
  hvs30: number
  hvs31: number
  hvs32: number
  hvs33: number
  hvs34: number
  hvs35: number
  hvs38: number
  hvventiayn: string
  hvventisoayn: string
  phpid: string
  rnum: number
  hv2?: number
  hv3?: number
  hv32?: number
  hv35?: number
  hv40?: number
  hvccc?: number
  hvs06?: number
  hvs07?: number
  hvs09?: number
  hvs16?: number
  hvs18?: number
  hvs24?: number
}
